name: pytest

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule: # Run every 3 hours starting at 10 minutes past the hour to avoid congestion (runs only on main branch).
    - cron: '10 */3 * * *'
  repository_dispatch: # Triggered by the "run plugin tests" workflow in the main repo (runs only on main branch).
    types: [run-plugin-tests]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] # Add windows-latest, macos-latest to test on multiple OS
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Install pre-release of CUQIpy # We install latest pre-release version of CUQIpy to catch upstream bugs early
        run: |
          pip uninstall cuqipy -y
          pip install -i https://test.pypi.org/simple/ cuqipy --pre --upgrade --no-cache-dir --force-reinstall
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          python -m pytest
