name: pytest

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-n-test:
    name: Build and test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] # Add windows-latest, macos-latest to test on multiple OS
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v3
#      - name: Install conda dependencies
#        run: | # Have to pin scipy to < 1.8.0 due to bug in CIL it seems.
#          conda install -c conda-forge -c intel -c astra-toolbox -c ccpi cil=22.1.0 astra-toolbox scipy=1.7.3
      - name: Install pip dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          python -m pytest -v
